name: Build & Release EPUBs

on:
  schedule:
    - cron: "0 0 1,15 * *"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
        env:
          PYTHONUTF8: 1

      - name: Install Python dependencies
        run: pip install Pillow

      - name: Process Images
        run: python scripts/images_epub.py
        env:
          PYTHONUTF8: 1
          PYTHONIOENCODING: utf-8

      - name: Build EPUBs
        run: python scripts/build_epub.py
        env:
          PYTHONUTF8: 1
          PYTHONIOENCODING: utf-8

      - name: Generate Release Tag
        id: tag
        shell: bash
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.tag.outputs.date }}
          name: EPUB v${{ steps.tag.outputs.date }}
          draft: false
          prerelease: false
          files: scripts/epub/*.epub
